Repository GreyTeam2020/GoOutSafe_Primer2020, pull requests merged in 2020-11, with the labels that each got.

#128 New tests for booking, restaurant and users
  monolith/services/restaurant_services.py
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/utils.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: tests

#122 Search restaurants by name or a sub string inside the name of restaurants
  monolith/database.py
  monolith/services/restaurant_services.py
  monolith/static/js/app.js
  monolith/templates/create_restaurant.html
  monolith/templates/footer.html
  monolith/templates/index.html
  monolith/templates/index_customer.html
  monolith/templates/navbar.html
  monolith/templates/user_data.html
  monolith/tests/conftest.py
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_healthy_services.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/utils.py
  monolith/views/home.py
  monolith/views/restaurants.py
Labels: enhancement, tests

#132 new Operator home and simpler footer
  monolith/static/styles/app.css
  monolith/templates/create_restaurant.html
  monolith/templates/footer.html
  monolith/templates/index_operator.html
  monolith/templates/norestaurant.html
  monolith/templates/restaurantsheet.html
  monolith/templates/users.html
  monolith/views/home.py
  monolith/views/restaurants.py
Labels: enhancement

#129 update booking; delete booking; checkin
  .travis.yml
  monolith/database.py
  monolith/forms.py
  monolith/services/booking_services.py
  monolith/services/restaurant_services.py
  monolith/services/user_service.py
  monolith/static/images/favicon/android-icon-144x144.png
  monolith/static/images/favicon/android-icon-192x192.png
  monolith/static/images/favicon/android-icon-36x36.png
  monolith/static/images/favicon/android-icon-48x48.png
  monolith/static/images/favicon/android-icon-72x72.png
  monolith/static/images/favicon/android-icon-96x96.png
  monolith/static/images/favicon/apple-icon-114x114.png
  monolith/static/images/favicon/apple-icon-120x120.png
  monolith/static/images/favicon/apple-icon-144x144.png
  monolith/static/images/favicon/apple-icon-152x152.png
  monolith/static/images/favicon/apple-icon-180x180.png
  monolith/static/images/favicon/apple-icon-57x57.png
  monolith/static/images/favicon/apple-icon-60x60.png
  monolith/static/images/favicon/apple-icon-72x72.png
  monolith/static/images/favicon/apple-icon-76x76.png
  monolith/static/images/favicon/apple-icon-precomposed.png
  monolith/static/images/favicon/apple-icon.png
  monolith/static/images/favicon/browserconfig.xml
  monolith/static/images/favicon/favicon-16x16.png
  monolith/static/images/favicon/favicon-32x32.png
  monolith/static/images/favicon/favicon-96x96.png
  monolith/static/images/favicon/favicon.ico
  monolith/static/images/favicon/manifest.json
  monolith/static/images/favicon/ms-icon-144x144.png
  monolith/static/images/favicon/ms-icon-150x150.png
  monolith/static/images/favicon/ms-icon-310x310.png
  monolith/static/images/favicon/ms-icon-70x70.png
  monolith/static/js/app.js
  monolith/templates/header.html
  monolith/templates/navbar/customer.html
  monolith/templates/reservations.html
  monolith/templates/user_reservations.html
  monolith/tests/fixtures/client.py
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/test_user_services.py
  monolith/utils/send_mail.py
  monolith/views/book.py
  monolith/views/health.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: enhancement, tests

#123 test Health services and view
  .coveralls.yml
  monolith/database.py
  monolith/forms.py
  monolith/services/booking_services.py
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/services/user_service.py
  monolith/templates/list_contacts.html
  monolith/templates/mark_positive.html
  monolith/templates/report_positive.html
  monolith/templates/search_contacts.html
  monolith/templates/unmark_positive.html
  monolith/tests/fixtures/client.py
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_healthy_services.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/utils.py
  monolith/utils/send_mail.py
  monolith/views/book.py
  monolith/views/health.py
  monolith/views/home.py
  monolith/views/restaurants.py
  monolith/views/users.py
  tox.ini
Labels: tests

#134 bug fixed in health authority
  monolith/database.py
  monolith/services/healthy_services.py
  monolith/templates/all_restaurants.html
  monolith/templates/navbar/health.html
  monolith/templates/report_positive.html
  monolith/tests/test_healthy_services.py
  monolith/utils/send_mail.py
  monolith/views/health.py
Labels: bug fix, enhancement

#130 Added comment inside the test class and formatting python code
  monolith/app_constant.py
  monolith/background.py
  monolith/database.py
  monolith/forms.py
  monolith/model/__init__.py
  monolith/model/restaurant_model.py
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/static/js/app.js
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_healthy_services.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/test_user_services.py
  monolith/utils/dispaccer_events.py
  monolith/utils/send_mail.py
  monolith/utils/send_mail.py~refs/remotes/origin/main
  monolith/views/book.py
  monolith/views/restaurants.py
Labels: documentation, enhancement, tests

#135 Friend mail list support and other fixes
  README.md
  monolith/database.py
  monolith/forms.py
  monolith/services/booking_services.py
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/templates/navbar/customer.html
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/utils.py
  monolith/views/book.py
  monolith/views/restaurants.py
Labels: DB changes, bug fix, enhancement

#148 Fixed refused and exception inside the email again
  Dockerfile
  docker-compose.yaml
  monolith/background.py
  monolith/utils/send_mail.py
  monolith/views/health.py
Labels: bug fix

#149 Clean test db with erase it
  monolith/services/booking_services.py
  monolith/templates/user_reservations.html
  monolith/tests/fixtures/client.py
  monolith/tests/gooutsafe.db-journal
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/utils.py
  monolith/views/book.py
Labels: bug fix

#150 fixed same day positive check
  .gitignore
  monolith/services/booking_services.py
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/static/js/app.js
  monolith/templates/reservations.html
  monolith/tests/fixtures/client.py
  monolith/tests/gooutsafe.db-journal
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_healthy_services.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/test_user_services.py
  monolith/tests/utils.py
  monolith/views/health.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: bug fix

#152 Rating restaurants with celery
  monolith/app.py
  monolith/app_constant.py
  monolith/background.py
  monolith/database.py
  monolith/services/__init__.py
  monolith/services/restaurant_services.py
  monolith/templates/index.html
  monolith/templates/index_customer.html
  monolith/templates/restaurantsheet.html
  monolith/tests/test_booking_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/utils.py
  monolith/utils/dispaccer_events.py
  monolith/views/home.py
  monolith/views/restaurants.py
Labels: enhancement

#155 Implement the notify method to all friends inside a reservation
  monolith/app_constant.py
  monolith/background.py
  monolith/services/booking_services.py
  monolith/tests/test_booking_services.py
  monolith/tests/utils.py
  monolith/utils/dispaccer_events.py
  monolith/utils/send_mail.py
Labels: enhancement

#157 fixed mark_positive
  .gitignore
  monolith/auth.py
  monolith/services/healthy_services.py
  monolith/tests/test_healthy_services.py
  monolith/tests/utils.py
Labels: bug fix

#151 Refactoring create users flask method and fixed bug #143
  .coveragerc
  monolith/database.py
  monolith/services/user_service.py
  monolith/templates/navbar/operator.html
  monolith/tests/test_user_services.py
  monolith/views/users.py
Labels: bug fix

#159 Fixed #153
  monolith/background.py
  monolith/services/healthy_services.py
  monolith/templates/restaurant_menu.html
  monolith/tests/test_healthy_services.py
  monolith/views/restaurants.py
Labels: bug fix

#162 Static report
  docker-compose.yaml
  monolith/app.py
  monolith/services/restaurant_services.py
  monolith/views/book.py
  monolith/views/home.py
Labels: enhancement

#164 Fixed celery periodic task and add more information on readme.
  README.md
  docker-compose.yaml
  monolith/__init__.py
  monolith/app.py
  monolith/app_constant.py
  monolith/background.py
  monolith/services/__init__.py
  monolith/services/healthy_services.py
  monolith/tests/test_healthy_services.py
  monolith/tests/utils.py
  monolith/utils/__init__.py
  monolith/utils/dispaccer_events.py
  monolith/utils/send_mail.py
  monolith/views/health.py
  monolith/views/home.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: bug fix, celery
