Repository GreyTeam2020/GoOutSafe_Primer2020, pull requests merged in 2020-10, with the labels that each got.

#1 Added support Docker and travis
  .travis.yml
  Dockerfile
  docker-compose.yaml
Labels: enhancement

#20 Fixed merge bugs
  monolith/templates/create_restaurant.html
  monolith/templates/create_user.html
  monolith/templates/index.html
  monolith/templates/login.html
  monolith/views/auth.py
  monolith/views/users.py
Labels: bug fix, merge, priority hight

#23 introduce the template of app.conf and managed error inside the UI from sql exception
  .gitignore
  monolith/app.py
  monolith/config/app.conf
  monolith/database.py
  monolith/templates/create_restaurant.html
  monolith/templates/create_user.html
  monolith/templates/login.html
  monolith/utils/SendMail.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: bug fix

#30 Adapted GUI to Composite Pattern and functional changes
  monolith/static/styles/app.css
  monolith/templates/booking.html
  monolith/templates/footer.html
  monolith/templates/header.html
  monolith/templates/index.html
  monolith/templates/navbar.html
  monolith/templates/navbar/admin.html
  monolith/templates/navbar/anonymous.html
  monolith/templates/navbar/customer.html
  monolith/templates/navbar/health.html
  monolith/templates/navbar/operator.html
  monolith/templates/restaurants.html
  monolith/templates/restaurantsheet.html
  monolith/templates/sendemailok.html
  monolith/templates/testtpl.html
  monolith/templates/users.html
  monolith/views/home.py
Labels: enhancement

#32 searchbar and book from restaurant view
  monolith/static/js/app.js
  monolith/templates/index.html
  monolith/templates/navbar.html
  monolith/templates/restaurantsheet.html
  monolith/views/restaurants.py
Labels: enhancement

#40 Fixed docker image
  Dockerfile
Labels: bug fix

#42 This is a draft version of porting UI on cosmo bootstrap
  monolith/templates/header.html
  monolith/templates/index.html
  monolith/templates/login.html
  monolith/templates/navbar.html
Labels: enhancement

#39 Fixed #33
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: enhancement

#41 Operator list reservations
  monolith/app.py
  monolith/auth.py
  monolith/database.py
  monolith/templates/list_reservations.html
  monolith/views/auth.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: DB changes, enhancement

#45 Introduction to flask unit tests
  .coverage
  .coveralls.yml
  .gitignore
  .travis.yml
  monolith/__init__.py
  monolith/config/app.config
  monolith/tests/conftest.py
  monolith/tests/fixtures/client.py
  monolith/tests/test_forms.py
  monolith/tests/utils.py
  monolith/utils/SendMail.py
  monolith/views/auth.py
  monolith/views/restaurants.py
Labels: enhancement, priority hight

#47 merge, change route in list reservation in restaurant
  monolith/views/restaurants.py
Labels: bug fix, enhancement

#52 added Map View
  monolith/static/js/app.js
  monolith/templates/header.html
  monolith/templates/index.html
Labels: enhancement

#56 Booking function
  monolith/app.py
  monolith/templates/booking.html
  monolith/views/book.py
Labels: enhancement

#60 Upload the test structure of the UI
  .coverage
  .coveralls.yml
  monolith/app.py
  monolith/auth.py
  monolith/database.py
  monolith/forms.py
  monolith/tests/test_forms.py
  monolith/views/auth.py
  monolith/views/book.py
  monolith/views/restaurants.py
Labels: priority hight, tests

#61 list reservation with new template, rename with a meaningful name the first data in app, add phone number to user
  .travis.yml
  monolith/app.py
  monolith/database.py
  monolith/templates/list_reservations.html
  monolith/templates/my_reservations.html
  monolith/tests/test_forms.py
  monolith/views/restaurants.py
Labels: enhancement

#69 my restaurant data and table managment GUI and skeleton
  monolith/forms.py
  monolith/static/js/app.js
  monolith/templates/my_reservations.html
  monolith/templates/my_restaurant_data.html
  monolith/templates/restaurantsheet.html
  monolith/views/auth.py
  monolith/views/restaurants.py
Labels: enhancement

#64 Increase battery test for the project (make travis the boss)
  .coverage
  .gitignore
  .travis.yml
  README.md
  monolith/forms.py
  monolith/tests/fixtures/client.py
  monolith/tests/test_forms.py
  monolith/tests/utils.py
Labels: priority hight, tests

#76 Make the test more stable
  monolith/tests/fixtures/client.py
  monolith/tests/test_forms.py
Labels: tests

#77 Introduce celery structure on docker
  Dockerfile
  build_and_run.sh
  docker-compose.yaml
  monolith/__init__.py
  monolith/app.py
  monolith/app_constant.py
  monolith/background.py
  monolith/config/app.config
  monolith/tests/test_forms.py
  monolith/utils/__init__.py
  monolith/utils/dispaccer_events.py
  monolith/utils/send_mail.py
  monolith/views/users.py
  requirements.txt
Labels: enhancement

#78 Introduction services
  monolith/services/__init__.py
  monolith/services/user_service.py
  monolith/tests/test_services.py
  monolith/utils/send_mail.py
  monolith/views/users.py
Labels: enhancement

#79 health authority mark people as infected
  monolith/auth.py
  monolith/database.py
  monolith/forms.py
  monolith/templates/index.html
  monolith/templates/mark_positive.html
  monolith/views/health.py
Labels: DB changes, enhancement

#82 Code formatting and upload the testing
  monolith/auth.py
  monolith/database.py
  monolith/forms.py
  monolith/services/__init__.py
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/test_user_services.py
  monolith/tests/utils.py
  monolith/views/health.py
  monolith/views/restaurants.py
Labels: tests

#85 healthy testing and implementation of services
  monolith/app.py
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/tests/test_forms.py
  monolith/tests/test_healthy_services.py
  monolith/tests/test_restaurant_services.py
  monolith/views/health.py
Labels: enhancement, tests

#89 Additional testing
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/tests/conftest.py
  monolith/tests/fixtures/__init__.py
  monolith/tests/fixtures/clean_db.py
  monolith/tests/fixtures/client.py
  monolith/tests/test_forms.py
  monolith/tests/test_healthy_services.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/test_user_services.py
  monolith/tests/utils.py
  monolith/views/auth.py
  monolith/views/health.py
  monolith/views/restaurants.py
Labels: tests

#81 some change and refactors
  monolith/database.py
  monolith/static/js/app.js
  monolith/templates/all_restaurants.html
  monolith/templates/header.html
  monolith/templates/index.html
  monolith/templates/login.html
  monolith/templates/menu.html
  monolith/templates/navbar/admin.html
  monolith/templates/navbar/customer.html
  monolith/templates/navbar/health.html
  monolith/templates/navbar/operator.html
  monolith/templates/photogallery.html
  monolith/templates/reservations.html
  monolith/templates/restaurant_data.html
  monolith/templates/restaurants.html
  monolith/templates/user_reservations.html
  monolith/tests/utils.py
  monolith/utils/__init__.py
  monolith/utils/formatter.py
  monolith/utils/send_mail.py
  monolith/utils/send_mail.py~refs/remotes/origin/main
  monolith/views/book.py
  monolith/views/health.py
  monolith/views/home.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: reafctoring

#93 health authority pr1 completed
  monolith/services/healthy_services.py
  monolith/templates/index.html
  monolith/templates/list_contacts.html
  monolith/templates/unmark_positive.html
  monolith/views/health.py
Labels: enhancement, tests

#95 Remove assertion on html and user hidden tag
  monolith/forms.py
  monolith/services/restaurant_services.py
  monolith/services/user_service.py
  monolith/templates/header.html
  monolith/templates/index.html
  monolith/templates/login.html
  monolith/templates/photogallery.html
  monolith/templates/restaurantsheet.html
  monolith/tests/test_forms.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/test_user_services.py
  monolith/views/auth.py
  monolith/views/health.py
  monolith/views/home.py
  monolith/views/restaurants.py
  monolith/views/users.py
  requirements.txt
Labels: tests

#97 Booking function fixed
  monolith/app.py
  monolith/database.py
  monolith/forms.py
  monolith/services/restaurant_services.py
  monolith/static/js/app.js
  monolith/templates/booking.html
  monolith/templates/restaurantsheet.html
  monolith/templates/review.html
  monolith/tests/test_forms.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/utils.py
  monolith/views/book.py
  monolith/views/restaurants.py
Labels: DB changes, tests

#102 Logic and test for modifying user data
  monolith/classes/__init__.py
  monolith/classes/restaurant.py
  monolith/classes/table.py
  monolith/classes/tests/rest0.txt
  monolith/classes/tests/test_restaurant.py
  monolith/services/user_service.py
  monolith/static/styles/app.css
  monolith/templates/navbar.html
  monolith/templates/navbar/customer.html
  monolith/templates/navbar/health.html
  monolith/templates/navbar/operator.html
  monolith/templates/user_data.html
  monolith/tests/test_user_services.py
  monolith/views/users.py
Labels: enhancement

#101 Increase tests and configured tox
  .travis.yml
  monolith/services/user_service.py
  monolith/views/users.py
  run-test-dev.sh
  tox.ini
Labels: tests

#106 Divided Signup
  monolith/forms.py
  monolith/services/healthy_services.py
  monolith/services/user_service.py
  monolith/templates/create_user.html
  monolith/templates/index_customer.html
  monolith/templates/navbar/operator.html
  monolith/templates/restaurantsheet.html
  monolith/templates/review.html
  monolith/views/health.py
  monolith/views/home.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: enhancement, tests

#121 Restaurant Menu with add/remove
  monolith/database.py
  monolith/forms.py
  monolith/services/healthy_services.py
  monolith/services/restaurant_services.py
  monolith/services/user_service.py
  monolith/templates/index.html
  monolith/templates/index_customer.html
  monolith/templates/index_operator.html
  monolith/templates/reservations.html
  monolith/templates/restaurant_menu.html
  monolith/templates/restaurantsheet.html
  monolith/tests/test_forms.py
  monolith/tests/test_restaurant_services.py
  monolith/tests/utils.py
  monolith/views/home.py
  monolith/views/restaurants.py
  monolith/views/users.py
Labels: DB changes, enhancement
